### ISSUE TITLE
Clumping index NetCDF file CI_2X_1Y_V2 does not have std column

### ISSUE THREAD

**Issue by eviatarbach** [CliMA/GriddingMachine.jl#75]
The NetCDF file that is downloaded for the clumping index, for `CI_2X_1Y_V2`, does not have an `std` column, so it gives an error when using `read_LUT`. `CI_2X_1Y_V1` does have it, however.

**Comment by Yujie-W** [comment]
I checked all the datasets now, and found that CI_2X_1Y_V2 did not have the field std (all rest datasets are okay). I fixed the CI_2X_1Y_V2 dataset, and you may use the latest one through updating GriddingMachine to v0.2.8.

If you are use v0.1, you may need to download and read the data manually.
